import styles from './AdminLanding.module.css'

export default function AdminLanding(){
    return(
        <>
        <div className={styles.container}>
            <p>Main content Lorem, ipsum dolor sit amet consectetur adipisicing elit. Animi, aperiam in dolore placeat blanditiis minima labore! Beatae quibusdam similique voluptas corporis veritatis dolorum fugiat eligendi perferendis minima voluptate aliquid in iste aperiam, id possimus ratione quas expedita velit explicabo repudiandae ipsam. Non illo corrupti cumque ex, aperiam sapiente fuga dolorum doloribus ullam ratione cum dolorem! Architecto nulla accusantium omnis placeat aspernatur illo iusto. Exercitationem quia totam consequuntur velit hic earum alias molestiae optio adipisci rem quidem, vitae quod tempora quasi cumque non tenetur ducimus atque nostrum perspiciatis facilis, libero quibusdam dolore assumenda! A eveniet nesciunt quos quibusdam distinctio, quas facere qui cupiditate nemo enim blanditiis alias, cumque sed rerum, beatae dolor laborum architecto? Voluptate vitae alias tempore, iusto explicabo qui tempora autem mollitia repellendus quis exercitationem nisi! Ducimus dicta accusamus quo sequi magni vel culpa eligendi molestiae doloremque, ad quaerat mollitia minus nisi esse veritatis qui, dignissimos ut maiores! Placeat, omnis. Pariatur iure omnis, culpa sequi dolorum tempora perferendis eveniet tempore quisquam non enim fugiat, eaque similique voluptates? Tempore voluptatum fuga culpa unde architecto enim repellendus quae beatae! Quidem autem maxime hic recusandae accusantium magni dolorum dolore! Minima vitae officiis harum, asperiores illum, dolor quos dolorem minus facere expedita consequatur.
                Llaborum, neque similique, repellat dolore. Eum sunt animi est et cupiditate veniam doloremque unde pariatur qndis, obcaecati quaerat aperiam error sunt alias deleniti dignissimos illum! Amet blanditiis expedita dignissimos repellendus repellat harum laudantium odio deserunt explicabo quia molestiae obcaecati voluptatem, sapiente exercitationem odit sunt velit ipsa minima hic beatae, consequuntur deleniti quo commodi maiores! Aperiam architecto ipsum exercitationem minus laborum a, non fugit, perferendis est officia voluptates iure nulla qui odio accusantium, vero dignissimos officiis placeat aliquam velit ducimus ea aut eius quos? Porro ratione natus adipisci. Odio recusandae exercitationem placeat quod eveniet!
            </p>
        </div>
        </>
    )
}